### ISSUE TITLE
binstar upload [SSLError] [SSL: CERTIFICATE_VERIFY_FAILED] win64 py34

### ISSUE THREAD

**Issue by faph** [Binstar/binstar#123]
Hi

Today, I started to get an `[SSLError] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed` error when doing `binstar upload`. It previously worked fine. Not sure if it's related to a recent update of some of the packages. My conda install looks like this:

```
             platform : win-64
        conda version : 3.9.0
  conda-build version : 1.10.2
       python version : 3.4.2.final.0
     requests version : 2.5.2
     root environment : C:\Program Files\Miniconda3  (read only)
  default environment : C:\Program Files\Miniconda3
     envs directories : C:\Users\fhollebrandse\.conda\envs
                        C:\Users\fhollebrandse\envs
                        C:\Program Files\Miniconda3\envs
        package cache : C:\Users\fhollebrandse\.conda\envs\.pkgs
                        C:\Users\fhollebrandse\envs\.pkgs
                        C:\Program Files\Miniconda3\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

And my root env like this:

```
binstar                   0.10.1                   py34_2
clyent                    0.3.2                    py34_0
conda                     3.9.0                    py34_0
conda-build               1.10.2                   py34_0
conda-env                 2.1.3                    py34_0
dateutil                  2.1                      py34_2
menuinst                  1.0.4                    py34_0
pip                       6.0.8                    py34_0
psutil                    2.1.1                    py34_0
pycosat                   0.6.1                    py34_0
python                    3.4.2                         0
python-dateutil           2.1                       <pip>
pytz                      2014.9                   py34_0
pyyaml                    3.11                     py34_0
requests                  2.5.2                    py34_0
setuptools                12.2                     py34_0
six                       1.9.0                    py34_0
```

`requests.get("https://api.binstar.org")` works fine.

Full error message:

```
PS C:\Users\fhollebrandse> binstar upload -c dev -u openhydrology c:\Users\fhollebrandse\Downloads\win-64_floodestimatio
n-0.3.3-np19py34_0.tar.bz2
Using binstar api site https://api.binstar.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file openhydrology/floodestimation/0.3.3/win-64/win-64_floodestimation-0.3.3-np19py34_0.tar.bz2 ...
[SSLError] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
Traceback (most recent call last):
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen

    body=body, headers=headers)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_r
equest
    self._validate_conn(conn)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 762, in _valida
te_conn
    conn.connect()
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 256, in ssl_wrap_soc
ket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Miniconda3\lib\ssl.py", line 364, in wrap_socket
    _context=self)
  File "C:\Program Files\Miniconda3\lib\ssl.py", line 578, in __init__
    self.do_handshake()
  File "C:\Program Files\Miniconda3\lib\ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 574, in urlopen

    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Miniconda3\Scripts\binstar-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Program Files\Miniconda3\lib\site-packages\binstar_client\scripts\cli.py", line 94, in main
    description=__doc__, version=version)
  File "C:\Program Files\Miniconda3\lib\site-packages\binstar_client\scripts\cli.py", line 76, in binstar_main
    return args.main(args)
  File "C:\Program Files\Miniconda3\lib\site-packages\binstar_client\commands\upload.py", line 202, in main
    callback=upload_print_callback(args))
  File "C:\Program Files\Miniconda3\lib\site-packages\binstar_client\__init__.py", line 423, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Miniconda3\lib\site-packages\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by fallen** [comment]
I have the same issue, I cannot upload any file on binstar anymore, either from Windows or from Linux (Debian Jessie). Same SSL error.
Even after a "conda update binstar" (so now I have up to date binstar client 0.10.1)

**Comment by srossross** [comment]
We are currently looking into this error. I suspect it may be the latest release of conda.

If you want a workaround, you can manage your binstar SSL verification settings with:
```
binstar config --set verify_ssl [true|false|/path/to/root/CA]
```

**Comment by fallen** [comment]
Just FYI, after a bit of wiresharking, it seems to be an issue with Amazon S3 storage SSL certificate.

**Comment by fallen** [comment]
Thanks for the workaround btw!

**Comment by faph** [comment]
Many thanks for looking into this. Workaround works well.

**Comment by faph** [comment]
Just to say, I get the same error on conda install and conda builds on my own channel. 

See for example this build on Travis CI: <https://travis-ci.org/OpenHydrology/floodestimation/jobs/51939331>

**Comment by faph** [comment]
It looks like this is solved with requests 2.5.3?

**Comment by faph** [comment]
Many thanks for all your help.

**Comment by niallobyrnes** [comment]
Still broken for channels.
binstar config --set verify_ssl false  not working around it either
